from FAdo.fa import *

def nfa_with_no_bridge_and_single_group():
    '''Fig 10'''
    nfa = NFA()
    nfa.setSigma(['a', 'b', 'c'])
    nfa.addState('0')
    nfa.addState('1')
    nfa.addState('2')
    nfa.addState('3')
    nfa.addState('4')
    nfa.setInitial([0])
    nfa.setFinal([4])
    nfa.addTransition(0, 'a', 1)
    nfa.addTransition(1, 'b', 3)
    nfa.addTransition(2, 'b', 1)
    nfa.addTransition(2, 'a', 2)
    nfa.addTransition(2, 'b', 2)
    nfa.addTransition(2, 'c', 2)
    nfa.addTransition(2, 'b', 3)
    nfa.addTransition(3, 'c', 2)
    nfa.addTransition(3, 'a', 4)
    return nfa

def get_fig8():
    fig8 = NFA()
    fig8.setSigma(['a', 'b'])
    fig8.addState('0')
    fig8.addState('1')
    fig8.addState('2')
    fig8.addState('3')
    fig8.addState('4')
    fig8.addState('5')
    fig8.addState('6')
    fig8.setInitial([0])
    fig8.setFinal([6])
    fig8.addTransition(0, 'b', 1)
    fig8.addTransition(0, 'b', 2)
    fig8.addTransition(1, 'b', 5)
    fig8.addTransition(2, 'a', 3)
    fig8.addTransition(2, 'b', 2)
    fig8.addTransition(3, 'a', 4)
    fig8.addTransition(4, 'b', 6)
    fig8.addTransition(5, 'a', 1)
    fig8.addTransition(5, 'a', 6)
    return fig8

def get_fig7():
    fig7 = NFA()
    fig7.setSigma(['a', 'b', 'c', 'd'])
    fig7.addState('0')
    fig7.addState('1')
    fig7.addState('2')
    fig7.addState('3')
    fig7.addState('4')
    fig7.setInitial([0])
    fig7.setFinal([4])
    fig7.addTransition(0, 'c', 1)
    fig7.addTransition(1, 'a', 2)
    fig7.addTransition(2, 'b', 2)
    fig7.addTransition(2, 'd', 1)
    fig7.addTransition(2, 'a', 3)
    fig7.addTransition(3, 'b', 4)
    return fig7

def nfa_for_identify_group_test():
    nfa = NFA()
    nfa.setSigma(['x'])
    nfa.addState('0')
    nfa.addState('1')
    nfa.addState('2')
    nfa.addState('3')
    nfa.addState('4')
    nfa.addState('5')
    nfa.setInitial([0])
    nfa.setFinal([5])
    nfa.addTransition(0, 'x', 1)
    nfa.addTransition(0, 'x', 2)
    nfa.addTransition(0, 'x', 3)
    nfa.addTransition(1, 'x', 4)
    nfa.addTransition(2, 'x', 4)
    nfa.addTransition(3, 'x', 5)
    nfa.addTransition(4, 'x', 5)
    return nfa